name: Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build_and_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decrypt private key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import -

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build and Sign Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --file ./Dockerfile.build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{github.repository}}/financial-web-app:latest \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }} \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.event_name }} \
            --push .
        env:
          DOCKER_CONTENT_TRUST: 1
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_SERVER: https://notary.docker.io

    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_TTY: $(tty)
