name: build and sign

on:
  push:
    branches:
      - 'main'

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write 

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/financial-web-app
          TAG=latest
          FULL_IMAGE_NAME=$IMAGE_NAME:$TAG
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --file ./Dockerfile.build \
            --platform linux/amd64,linux/arm64 \
            --tag $FULL_IMAGE_NAME \
            --output=type=registry \
            --push .
          echo "FULL_IMAGE_NAME=$FULL_IMAGE_NAME" >> $GITHUB_ENV

      - name: Get Image Digest
        run: |
          DIGEST=$(docker buildx imagetools inspect ${{ env.FULL_IMAGE_NAME }} | grep Digest | sed 's/Digest: //')
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.DIGEST }}
        env:
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      # Add steps for scanning for vulnerabilities or any other post-processing steps here
