name: Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build_and_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --file ./Dockerfile.build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{github.repository}}/financial-web-app:latest \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }} \
            --push .

      - name: Install Cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/download/v1.5.2/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker Image
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | cosign sign -key /dev/stdin ghcr.io/${{github.repository}}/financial-web-app:latest
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | cosign sign -key /dev/stdin ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }}
