name: Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build, Sign, and Scan Container Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --file ./Dockerfile.build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{github.repository}}/financial-web-app:latest \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }} \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.event_name }} \
            --push .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'

      - name: Set up Docker Buildx for Signing
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Sign Docker Image
        run: |
          docker buildx build \
            --file ./Dockerfile.build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{github.repository}}/financial-web-app:latest \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }} \
            --tag ghcr.io/${{github.repository}}/financial-web-app:${{ github.event_name }} \
            --push .
        env:
          DOCKER_CONTENT_TRUST: 1
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_SERVER: https://notary.docker.io

    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_TTY: $(tty)

  - name: Scan for vulnerabilities
    uses: crazy-max/ghaction-container-scan@v3
    with:
      image: ghcr.io/${{github.repository}}/financial-web-app:${{ github.sha }}
